export const hitokotoList = [
  { hitokoto: "人生没有白走的路，每一步都算数。", from: "佚名" },
  { hitokoto: "生活不止眼前的苟且，还有诗和远方。", from: "高晓松" },
  { hitokoto: "岁月静好，现世安稳。", from: "胡兰成" },
  { hitokoto: "不忘初心，方得始终。", from: "华严经" },
  { hitokoto: "愿你历尽千帆，归来仍是少年。", from: "佚名" },
  { hitokoto: "生活明朗，万物可爱。", from: "佚名" },
  { hitokoto: "心怀浪漫宇宙，也珍惜人间日常。", from: "佚名" },
  { hitokoto: "慢慢来，比较快。", from: "佚名" },
  { hitokoto: "人生没有太晚的开始。", from: "摩西奶奶" },
  { hitokoto: "相信美好，美好就会遇见。", from: "佚名" },
  { hitokoto: "愿所有美好如期而至。", from: "佚名" },
  { hitokoto: "时光不语，静待花开。", from: "佚名" },
  { hitokoto: "把日子过成诗。", from: "佚名" },
  { hitokoto: "心若向阳，无畏悲伤。", from: "佚名" },
  { hitokoto: "做自己的太阳，无需借助谁的光。", from: "佚名" },
  { hitokoto: "愿你眼中有星辰，心中有山海。", from: "佚名" },
  { hitokoto: "生活明朗，未来可期。", from: "佚名" },
  { hitokoto: "不负时光，不负自己。", from: "佚名" },
  { hitokoto: "今日份小美好。", from: "佚名" },
  { hitokoto: "人间值得，未来可期。", from: "佚名" },
];
